### ISSUE TITLE
Google Optimize

### ISSUE THREAD

**Issue by gety9** [MartijnSch/cro#8]
Guys hi,

It's more a question than an issue.

I am considering 2 possible approaches to A/B testing

1st - GTM + your script + google analytics 
2nd - GTM+ Google Optimize

Could you compare these 2 solutions? 

What are the cons and pros of each?﻿

**Comment by MartijnSch** [comment]
Hi, So what's good to realize is that this script was developed before Google Optimize was released. Our team at TNW was actually involved in some early BETA testing of Google Optimize as well and their product is working pretty flawless. My take on it these days is that it's probably for most companies easiest to use Google Optimize (outside of GTM to have the ability to deal with the page hiding).

**Comment by gety9** [comment]
@MartijnSch 

Thank you for your reply,

I do realize that Google Optimize came way after your solution which you were kind to share with people.

I just wanted to check if it still made sense to use it.
